package game.model;
// Generated Nov 29, 2023, 4:56:05 PM by Hibernate Tools 5.4.33.Final

import java.util.HashSet;
import java.util.Set;

/**
 * ConsumableItem generated by hbm2java
 */
public class ConsumableItem implements java.io.Serializable {

	private int itemId;
	private Item item;
	private int itemLevel;
	private String itemDescription;
	private Set consumableItemEffects = new HashSet(0);

	public ConsumableItem() {
	}

	public ConsumableItem(Item item, int itemLevel, String itemDescription) {
		this.item = item;
		this.itemLevel = itemLevel;
		this.itemDescription = itemDescription;
	}

	public ConsumableItem(Item item, int itemLevel, String itemDescription, Set consumableItemEffects) {
		this.item = item;
		this.itemLevel = itemLevel;
		this.itemDescription = itemDescription;
		this.consumableItemEffects = consumableItemEffects;
	}

	public int getItemId() {
		return this.itemId;
	}

	public void setItemId(int itemId) {
		this.itemId = itemId;
	}

	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	public int getItemLevel() {
		return this.itemLevel;
	}

	public void setItemLevel(int itemLevel) {
		this.itemLevel = itemLevel;
	}

	public String getItemDescription() {
		return this.itemDescription;
	}

	public void setItemDescription(String itemDescription) {
		this.itemDescription = itemDescription;
	}

	public Set getConsumableItemEffects() {
		return this.consumableItemEffects;
	}

	public void setConsumableItemEffects(Set consumableItemEffects) {
		this.consumableItemEffects = consumableItemEffects;
	}

}
