package game.model;
// Generated Nov 29, 2023, 4:56:05 PM by Hibernate Tools 5.4.33.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Player generated by hbm2java
 */
public class Player implements java.io.Serializable {

	private Integer playerId;
	private String playerName;
	private String email;
	private String playerPassword;
	private Set gameCharacters = new HashSet(0);

	public Player() {
	}

	public Player(String playerName, String email, String playerPassword) {
		this.playerName = playerName;
		this.email = email;
		this.playerPassword = playerPassword;
	}

	public Player(String playerName, String email, String playerPassword, Set gameCharacters) {
		this.playerName = playerName;
		this.email = email;
		this.playerPassword = playerPassword;
		this.gameCharacters = gameCharacters;
	}

	public Integer getPlayerId() {
		return this.playerId;
	}

	public void setPlayerId(Integer playerId) {
		this.playerId = playerId;
	}

	public String getPlayerName() {
		return this.playerName;
	}

	public void setPlayerName(String playerName) {
		this.playerName = playerName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPlayerPassword() {
		return this.playerPassword;
	}

	public void setPlayerPassword(String playerPassword) {
		this.playerPassword = playerPassword;
	}

	public Set getGameCharacters() {
		return this.gameCharacters;
	}

	public void setGameCharacters(Set gameCharacters) {
		this.gameCharacters = gameCharacters;
	}

}
